name: ci
on: [push]
jobs:
  ci:
    timeout-minutes: 20
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        name: Use Node.js 13.x
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: "13.x"
      - uses: actions/cache@v1
        name: Restore node_modules cache
        id: node_modules
        with:
          path: node_modules
          key: ${{runner.os}}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.os}}-node_modules
      - run: npm ci
        if: steps.node_modules.outputs.cache-hit != 'true'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - run: npm run test
